### ISSUE TITLE
Scheduling research sessions

### ISSUE THREAD

**Issue by arouault** [18F/SNAP-Retailer-Authorization#1]
- [x] Send ROB request to Karen
- [x] Reach out to ROB participants to schedule (7/24) - Ryan
- [x] Investigate best way to identify retailer participants - Ryan will coordinate with Nicole on best way to pull a list
- [x] Schedule retailer participants
- [x] Schedule SME interviews
- - [x] Shelley - Ryan - schedule for next week
- - [x] Ventera - Ryan - schedule for next week
- - [x] Henry - Ryan - schedule for next week

**Comment by arouault** [comment]
Update on Retailer participants: Candyce and Josh gave us a bunch of stores to reach out to
Ryan to pull Claudia's batch [7/29]
Tomorrow [7/30]

**Comment by arouault** [comment]
- [x] Ryan has David and John Coulter as stand-ins for Marci

**Comment by arouault** [comment]
Retailers are in NY and Boston from Candyce and Josh!

**Comment by ryanschreibr** [comment]
Claudia M. identified 5 stores which received assistance in Spanish from the RSC. We should have a complete list of retailers for interviews.
