### ISSUE TITLE
Create Agenda for Mid-Way Briefing with Nicole & Andrea

### ISSUE THREAD

**Issue by ryanschreibr** [18F/SNAP-Retailer-Authorization#19]
Need to updated calendar invite with an agenda for the meeting by 8/19.

**Comment by ryanschreibr** [comment]
Need to updated calendar invite with an agenda for the meeting by 8/19.

**Comment by NorahMaki** [comment]
@NorahMaki and @arouault to put together first draft; share with @ryanschreibr and @jgounder and Candyce for inputs
