### ISSUE TITLE
Decide on process for documenting desk research findings for future synthesis

### ISSUE THREAD

**Issue by arouault** [18F/SNAP-Retailer-Authorization#2]

**Comment by arouault** [comment]
We'll keep doing this moving forward, together!

**Comment by NorahMaki** [comment]
Will use this mural to capture key findings as we go. Reviewed the process in our weekly sync on 7/29 https://app.mural.co/t/gsa6/m/gsa6/1564145321135/956cd3418102915f279e6a6c484da6ee97089b12
